#!/bin/bash

set -Eefu -o pipefail

echo "--- Merge commit plugin"

echo "Original commit:"
git --no-pager log -n 1

if [[ "${BUILDKITE_PULL_REQUEST:?}" == "false" ]]; then
    echo "This is not a pull request."
else
    echo "This is a pull request."
    echo "Pull request number: ${BUILDKITE_PULL_REQUEST:?}"
    sleep 3 # Give GitHub a few seconds to create the merge commit.
    echo "Fetching the merge commit from origin"
    git fetch origin "+refs/pull/${BUILDKITE_PULL_REQUEST:?}/merge"
    echo "Checking out the merge commit"
    git checkout --force FETCH_HEAD
    echo "The merge commit is:"
    git --no-pager log -n 1
fi
